nsURL = "https://MyNightscoutURL.herokuapp.com/" # or perhaps like "https://MyNightscoutURL.azurewebsites.net/"
nsToken="subjectname-hash"
dexUsername = "MyDexUsername" # replace with your username
dexPassword = "MyDexPassword" #replace with your password
glucoseUnit = "mg/dL" # selected unit mg/dL or mmmol/L
carbRatio = 12 # grams of carbohydrate per unit of fast-acting insulin
ISF = 40 # mg/dL or mmol/L per unit fast-acting insulin
CSF = ISF / carbRatio # mg/dL or mmol/L per gram of carbohydrate
carbsPerSkittle = 0.88 # grams of carbohydrate per Skittle
lowGlucoseThreshold = 70 # mg/dL or mmol/L, below which the user requires Skittles
treatmentTarget = 90 # mg/dL or mmol/L, the target glucose to treat to
maxSkittles = 10 # maximum Skittles to deliver on a button press; don't want a ridiculous calculation to deliver some crazy amount
oprahMode = True # YOU GET A SKITTLE! YOU GET A SKITTLE! EVERYBODY GETS A SKITTLE! http://knowyourmeme.com/memes/oprahs-you-get-a-car